#!/usr/bin/bash

if [[ ! -f release.properties ]]; then
    echo "Need to prepare release first."
    exit 1
fi
mvn release:perform
echo
echo "Don't forgot push the changes and tags for this release."
echo "After a successful release, execute e.g. 'git push' and 'git push --tags'."
