#!/usr/bin/bash

##############################################################################
# Copyright (c) 2020-2025 John Whaley and com.github.javabdd contributors
#
# See the CONTRIBUTORS file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the GNU Library General Public License v2 or later, which is
# available at https://spdx.org/licenses/LGPL-2.0-or-later.html
#
# SPDX-License-Identifier: LGPL-2.0-or-later
##############################################################################

if [[ ! -f release.properties ]]; then
    echo "Need to prepare release first."
    exit 1
fi
mvn release:perform
echo
echo "Don't forgot push the changes and tags for this release."
echo "After a successful release, execute e.g. 'git push' and 'git push --tags'."
