#!/bin/bash

### echo Directory is $1
shift

for arg in "$@"
do
 if [ ".java" == .${arg##*.} ]
 then
  if [ -e $arg ]
  then
   if grep -l "	" $arg
   then
    echo "Tab characters not allowed!  Use spaces or \\t instead."
    exit 1
   fi
  fi
 fi
done

exit 0
